/*
 * PosixFilePermissionSupportTest.java
 * Copyright 2016 Rob Spoor
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.robtimus.filesystems.attribute;

import static org.junit.Assert.assertEquals;
import java.nio.file.attribute.PosixFilePermission;
import java.nio.file.attribute.PosixFilePermissions;
import java.util.Arrays;
import java.util.Set;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

@RunWith(Parameterized.class)
@SuppressWarnings({ "nls", "javadoc" })
public class PosixFilePermissionSupportTest {

    private static final PosixFilePermission[] ALL_PERMISSIONS = PosixFilePermission.values();

    private final int mask;
    private final Set<PosixFilePermission> permissions;

    public PosixFilePermissionSupportTest(int mask, String permissions) {
        this.mask = mask;
        this.permissions = PosixFilePermissions.fromString(permissions);
    }

    @Parameters(name = "mask: {0}, permissions: {1}")
    public static Iterable<Object[]> getParameters() {
        Object[][] parameters = {
                { 0000, "---------", },
                { 0001, "--------x", },
                { 0002, "-------w-", },
                { 0003, "-------wx", },
                { 0004, "------r--", },
                { 0005, "------r-x", },
                { 0006, "------rw-", },
                { 0007, "------rwx", },
                { 0010, "-----x---", },
                { 0011, "-----x--x", },
                { 0012, "-----x-w-", },
                { 0013, "-----x-wx", },
                { 0014, "-----xr--", },
                { 0015, "-----xr-x", },
                { 0016, "-----xrw-", },
                { 0017, "-----xrwx", },
                { 0020, "----w----", },
                { 0021, "----w---x", },
                { 0022, "----w--w-", },
                { 0023, "----w--wx", },
                { 0024, "----w-r--", },
                { 0025, "----w-r-x", },
                { 0026, "----w-rw-", },
                { 0027, "----w-rwx", },
                { 0030, "----wx---", },
                { 0031, "----wx--x", },
                { 0032, "----wx-w-", },
                { 0033, "----wx-wx", },
                { 0034, "----wxr--", },
                { 0035, "----wxr-x", },
                { 0036, "----wxrw-", },
                { 0037, "----wxrwx", },
                { 0040, "---r-----", },
                { 0041, "---r----x", },
                { 0042, "---r---w-", },
                { 0043, "---r---wx", },
                { 0044, "---r--r--", },
                { 0045, "---r--r-x", },
                { 0046, "---r--rw-", },
                { 0047, "---r--rwx", },
                { 0050, "---r-x---", },
                { 0051, "---r-x--x", },
                { 0052, "---r-x-w-", },
                { 0053, "---r-x-wx", },
                { 0054, "---r-xr--", },
                { 0055, "---r-xr-x", },
                { 0056, "---r-xrw-", },
                { 0057, "---r-xrwx", },
                { 0060, "---rw----", },
                { 0061, "---rw---x", },
                { 0062, "---rw--w-", },
                { 0063, "---rw--wx", },
                { 0064, "---rw-r--", },
                { 0065, "---rw-r-x", },
                { 0066, "---rw-rw-", },
                { 0067, "---rw-rwx", },
                { 0070, "---rwx---", },
                { 0071, "---rwx--x", },
                { 0072, "---rwx-w-", },
                { 0073, "---rwx-wx", },
                { 0074, "---rwxr--", },
                { 0075, "---rwxr-x", },
                { 0076, "---rwxrw-", },
                { 0077, "---rwxrwx", },
                { 0100, "--x------", },
                { 0101, "--x-----x", },
                { 0102, "--x----w-", },
                { 0103, "--x----wx", },
                { 0104, "--x---r--", },
                { 0105, "--x---r-x", },
                { 0106, "--x---rw-", },
                { 0107, "--x---rwx", },
                { 0110, "--x--x---", },
                { 0111, "--x--x--x", },
                { 0112, "--x--x-w-", },
                { 0113, "--x--x-wx", },
                { 0114, "--x--xr--", },
                { 0115, "--x--xr-x", },
                { 0116, "--x--xrw-", },
                { 0117, "--x--xrwx", },
                { 0120, "--x-w----", },
                { 0121, "--x-w---x", },
                { 0122, "--x-w--w-", },
                { 0123, "--x-w--wx", },
                { 0124, "--x-w-r--", },
                { 0125, "--x-w-r-x", },
                { 0126, "--x-w-rw-", },
                { 0127, "--x-w-rwx", },
                { 0130, "--x-wx---", },
                { 0131, "--x-wx--x", },
                { 0132, "--x-wx-w-", },
                { 0133, "--x-wx-wx", },
                { 0134, "--x-wxr--", },
                { 0135, "--x-wxr-x", },
                { 0136, "--x-wxrw-", },
                { 0137, "--x-wxrwx", },
                { 0140, "--xr-----", },
                { 0141, "--xr----x", },
                { 0142, "--xr---w-", },
                { 0143, "--xr---wx", },
                { 0144, "--xr--r--", },
                { 0145, "--xr--r-x", },
                { 0146, "--xr--rw-", },
                { 0147, "--xr--rwx", },
                { 0150, "--xr-x---", },
                { 0151, "--xr-x--x", },
                { 0152, "--xr-x-w-", },
                { 0153, "--xr-x-wx", },
                { 0154, "--xr-xr--", },
                { 0155, "--xr-xr-x", },
                { 0156, "--xr-xrw-", },
                { 0157, "--xr-xrwx", },
                { 0160, "--xrw----", },
                { 0161, "--xrw---x", },
                { 0162, "--xrw--w-", },
                { 0163, "--xrw--wx", },
                { 0164, "--xrw-r--", },
                { 0165, "--xrw-r-x", },
                { 0166, "--xrw-rw-", },
                { 0167, "--xrw-rwx", },
                { 0170, "--xrwx---", },
                { 0171, "--xrwx--x", },
                { 0172, "--xrwx-w-", },
                { 0173, "--xrwx-wx", },
                { 0174, "--xrwxr--", },
                { 0175, "--xrwxr-x", },
                { 0176, "--xrwxrw-", },
                { 0177, "--xrwxrwx", },
                { 0200, "-w-------", },
                { 0201, "-w------x", },
                { 0202, "-w-----w-", },
                { 0203, "-w-----wx", },
                { 0204, "-w----r--", },
                { 0205, "-w----r-x", },
                { 0206, "-w----rw-", },
                { 0207, "-w----rwx", },
                { 0210, "-w---x---", },
                { 0211, "-w---x--x", },
                { 0212, "-w---x-w-", },
                { 0213, "-w---x-wx", },
                { 0214, "-w---xr--", },
                { 0215, "-w---xr-x", },
                { 0216, "-w---xrw-", },
                { 0217, "-w---xrwx", },
                { 0220, "-w--w----", },
                { 0221, "-w--w---x", },
                { 0222, "-w--w--w-", },
                { 0223, "-w--w--wx", },
                { 0224, "-w--w-r--", },
                { 0225, "-w--w-r-x", },
                { 0226, "-w--w-rw-", },
                { 0227, "-w--w-rwx", },
                { 0230, "-w--wx---", },
                { 0231, "-w--wx--x", },
                { 0232, "-w--wx-w-", },
                { 0233, "-w--wx-wx", },
                { 0234, "-w--wxr--", },
                { 0235, "-w--wxr-x", },
                { 0236, "-w--wxrw-", },
                { 0237, "-w--wxrwx", },
                { 0240, "-w-r-----", },
                { 0241, "-w-r----x", },
                { 0242, "-w-r---w-", },
                { 0243, "-w-r---wx", },
                { 0244, "-w-r--r--", },
                { 0245, "-w-r--r-x", },
                { 0246, "-w-r--rw-", },
                { 0247, "-w-r--rwx", },
                { 0250, "-w-r-x---", },
                { 0251, "-w-r-x--x", },
                { 0252, "-w-r-x-w-", },
                { 0253, "-w-r-x-wx", },
                { 0254, "-w-r-xr--", },
                { 0255, "-w-r-xr-x", },
                { 0256, "-w-r-xrw-", },
                { 0257, "-w-r-xrwx", },
                { 0260, "-w-rw----", },
                { 0261, "-w-rw---x", },
                { 0262, "-w-rw--w-", },
                { 0263, "-w-rw--wx", },
                { 0264, "-w-rw-r--", },
                { 0265, "-w-rw-r-x", },
                { 0266, "-w-rw-rw-", },
                { 0267, "-w-rw-rwx", },
                { 0270, "-w-rwx---", },
                { 0271, "-w-rwx--x", },
                { 0272, "-w-rwx-w-", },
                { 0273, "-w-rwx-wx", },
                { 0274, "-w-rwxr--", },
                { 0275, "-w-rwxr-x", },
                { 0276, "-w-rwxrw-", },
                { 0277, "-w-rwxrwx", },
                { 0300, "-wx------", },
                { 0301, "-wx-----x", },
                { 0302, "-wx----w-", },
                { 0303, "-wx----wx", },
                { 0304, "-wx---r--", },
                { 0305, "-wx---r-x", },
                { 0306, "-wx---rw-", },
                { 0307, "-wx---rwx", },
                { 0310, "-wx--x---", },
                { 0311, "-wx--x--x", },
                { 0312, "-wx--x-w-", },
                { 0313, "-wx--x-wx", },
                { 0314, "-wx--xr--", },
                { 0315, "-wx--xr-x", },
                { 0316, "-wx--xrw-", },
                { 0317, "-wx--xrwx", },
                { 0320, "-wx-w----", },
                { 0321, "-wx-w---x", },
                { 0322, "-wx-w--w-", },
                { 0323, "-wx-w--wx", },
                { 0324, "-wx-w-r--", },
                { 0325, "-wx-w-r-x", },
                { 0326, "-wx-w-rw-", },
                { 0327, "-wx-w-rwx", },
                { 0330, "-wx-wx---", },
                { 0331, "-wx-wx--x", },
                { 0332, "-wx-wx-w-", },
                { 0333, "-wx-wx-wx", },
                { 0334, "-wx-wxr--", },
                { 0335, "-wx-wxr-x", },
                { 0336, "-wx-wxrw-", },
                { 0337, "-wx-wxrwx", },
                { 0340, "-wxr-----", },
                { 0341, "-wxr----x", },
                { 0342, "-wxr---w-", },
                { 0343, "-wxr---wx", },
                { 0344, "-wxr--r--", },
                { 0345, "-wxr--r-x", },
                { 0346, "-wxr--rw-", },
                { 0347, "-wxr--rwx", },
                { 0350, "-wxr-x---", },
                { 0351, "-wxr-x--x", },
                { 0352, "-wxr-x-w-", },
                { 0353, "-wxr-x-wx", },
                { 0354, "-wxr-xr--", },
                { 0355, "-wxr-xr-x", },
                { 0356, "-wxr-xrw-", },
                { 0357, "-wxr-xrwx", },
                { 0360, "-wxrw----", },
                { 0361, "-wxrw---x", },
                { 0362, "-wxrw--w-", },
                { 0363, "-wxrw--wx", },
                { 0364, "-wxrw-r--", },
                { 0365, "-wxrw-r-x", },
                { 0366, "-wxrw-rw-", },
                { 0367, "-wxrw-rwx", },
                { 0370, "-wxrwx---", },
                { 0371, "-wxrwx--x", },
                { 0372, "-wxrwx-w-", },
                { 0373, "-wxrwx-wx", },
                { 0374, "-wxrwxr--", },
                { 0375, "-wxrwxr-x", },
                { 0376, "-wxrwxrw-", },
                { 0377, "-wxrwxrwx", },
                { 0400, "r--------", },
                { 0401, "r-------x", },
                { 0402, "r------w-", },
                { 0403, "r------wx", },
                { 0404, "r-----r--", },
                { 0405, "r-----r-x", },
                { 0406, "r-----rw-", },
                { 0407, "r-----rwx", },
                { 0410, "r----x---", },
                { 0411, "r----x--x", },
                { 0412, "r----x-w-", },
                { 0413, "r----x-wx", },
                { 0414, "r----xr--", },
                { 0415, "r----xr-x", },
                { 0416, "r----xrw-", },
                { 0417, "r----xrwx", },
                { 0420, "r---w----", },
                { 0421, "r---w---x", },
                { 0422, "r---w--w-", },
                { 0423, "r---w--wx", },
                { 0424, "r---w-r--", },
                { 0425, "r---w-r-x", },
                { 0426, "r---w-rw-", },
                { 0427, "r---w-rwx", },
                { 0430, "r---wx---", },
                { 0431, "r---wx--x", },
                { 0432, "r---wx-w-", },
                { 0433, "r---wx-wx", },
                { 0434, "r---wxr--", },
                { 0435, "r---wxr-x", },
                { 0436, "r---wxrw-", },
                { 0437, "r---wxrwx", },
                { 0440, "r--r-----", },
                { 0441, "r--r----x", },
                { 0442, "r--r---w-", },
                { 0443, "r--r---wx", },
                { 0444, "r--r--r--", },
                { 0445, "r--r--r-x", },
                { 0446, "r--r--rw-", },
                { 0447, "r--r--rwx", },
                { 0450, "r--r-x---", },
                { 0451, "r--r-x--x", },
                { 0452, "r--r-x-w-", },
                { 0453, "r--r-x-wx", },
                { 0454, "r--r-xr--", },
                { 0455, "r--r-xr-x", },
                { 0456, "r--r-xrw-", },
                { 0457, "r--r-xrwx", },
                { 0460, "r--rw----", },
                { 0461, "r--rw---x", },
                { 0462, "r--rw--w-", },
                { 0463, "r--rw--wx", },
                { 0464, "r--rw-r--", },
                { 0465, "r--rw-r-x", },
                { 0466, "r--rw-rw-", },
                { 0467, "r--rw-rwx", },
                { 0470, "r--rwx---", },
                { 0471, "r--rwx--x", },
                { 0472, "r--rwx-w-", },
                { 0473, "r--rwx-wx", },
                { 0474, "r--rwxr--", },
                { 0475, "r--rwxr-x", },
                { 0476, "r--rwxrw-", },
                { 0477, "r--rwxrwx", },
                { 0500, "r-x------", },
                { 0501, "r-x-----x", },
                { 0502, "r-x----w-", },
                { 0503, "r-x----wx", },
                { 0504, "r-x---r--", },
                { 0505, "r-x---r-x", },
                { 0506, "r-x---rw-", },
                { 0507, "r-x---rwx", },
                { 0510, "r-x--x---", },
                { 0511, "r-x--x--x", },
                { 0512, "r-x--x-w-", },
                { 0513, "r-x--x-wx", },
                { 0514, "r-x--xr--", },
                { 0515, "r-x--xr-x", },
                { 0516, "r-x--xrw-", },
                { 0517, "r-x--xrwx", },
                { 0520, "r-x-w----", },
                { 0521, "r-x-w---x", },
                { 0522, "r-x-w--w-", },
                { 0523, "r-x-w--wx", },
                { 0524, "r-x-w-r--", },
                { 0525, "r-x-w-r-x", },
                { 0526, "r-x-w-rw-", },
                { 0527, "r-x-w-rwx", },
                { 0530, "r-x-wx---", },
                { 0531, "r-x-wx--x", },
                { 0532, "r-x-wx-w-", },
                { 0533, "r-x-wx-wx", },
                { 0534, "r-x-wxr--", },
                { 0535, "r-x-wxr-x", },
                { 0536, "r-x-wxrw-", },
                { 0537, "r-x-wxrwx", },
                { 0540, "r-xr-----", },
                { 0541, "r-xr----x", },
                { 0542, "r-xr---w-", },
                { 0543, "r-xr---wx", },
                { 0544, "r-xr--r--", },
                { 0545, "r-xr--r-x", },
                { 0546, "r-xr--rw-", },
                { 0547, "r-xr--rwx", },
                { 0550, "r-xr-x---", },
                { 0551, "r-xr-x--x", },
                { 0552, "r-xr-x-w-", },
                { 0553, "r-xr-x-wx", },
                { 0554, "r-xr-xr--", },
                { 0555, "r-xr-xr-x", },
                { 0556, "r-xr-xrw-", },
                { 0557, "r-xr-xrwx", },
                { 0560, "r-xrw----", },
                { 0561, "r-xrw---x", },
                { 0562, "r-xrw--w-", },
                { 0563, "r-xrw--wx", },
                { 0564, "r-xrw-r--", },
                { 0565, "r-xrw-r-x", },
                { 0566, "r-xrw-rw-", },
                { 0567, "r-xrw-rwx", },
                { 0570, "r-xrwx---", },
                { 0571, "r-xrwx--x", },
                { 0572, "r-xrwx-w-", },
                { 0573, "r-xrwx-wx", },
                { 0574, "r-xrwxr--", },
                { 0575, "r-xrwxr-x", },
                { 0576, "r-xrwxrw-", },
                { 0577, "r-xrwxrwx", },
                { 0600, "rw-------", },
                { 0601, "rw------x", },
                { 0602, "rw-----w-", },
                { 0603, "rw-----wx", },
                { 0604, "rw----r--", },
                { 0605, "rw----r-x", },
                { 0606, "rw----rw-", },
                { 0607, "rw----rwx", },
                { 0610, "rw---x---", },
                { 0611, "rw---x--x", },
                { 0612, "rw---x-w-", },
                { 0613, "rw---x-wx", },
                { 0614, "rw---xr--", },
                { 0615, "rw---xr-x", },
                { 0616, "rw---xrw-", },
                { 0617, "rw---xrwx", },
                { 0620, "rw--w----", },
                { 0621, "rw--w---x", },
                { 0622, "rw--w--w-", },
                { 0623, "rw--w--wx", },
                { 0624, "rw--w-r--", },
                { 0625, "rw--w-r-x", },
                { 0626, "rw--w-rw-", },
                { 0627, "rw--w-rwx", },
                { 0630, "rw--wx---", },
                { 0631, "rw--wx--x", },
                { 0632, "rw--wx-w-", },
                { 0633, "rw--wx-wx", },
                { 0634, "rw--wxr--", },
                { 0635, "rw--wxr-x", },
                { 0636, "rw--wxrw-", },
                { 0637, "rw--wxrwx", },
                { 0640, "rw-r-----", },
                { 0641, "rw-r----x", },
                { 0642, "rw-r---w-", },
                { 0643, "rw-r---wx", },
                { 0644, "rw-r--r--", },
                { 0645, "rw-r--r-x", },
                { 0646, "rw-r--rw-", },
                { 0647, "rw-r--rwx", },
                { 0650, "rw-r-x---", },
                { 0651, "rw-r-x--x", },
                { 0652, "rw-r-x-w-", },
                { 0653, "rw-r-x-wx", },
                { 0654, "rw-r-xr--", },
                { 0655, "rw-r-xr-x", },
                { 0656, "rw-r-xrw-", },
                { 0657, "rw-r-xrwx", },
                { 0660, "rw-rw----", },
                { 0661, "rw-rw---x", },
                { 0662, "rw-rw--w-", },
                { 0663, "rw-rw--wx", },
                { 0664, "rw-rw-r--", },
                { 0665, "rw-rw-r-x", },
                { 0666, "rw-rw-rw-", },
                { 0667, "rw-rw-rwx", },
                { 0670, "rw-rwx---", },
                { 0671, "rw-rwx--x", },
                { 0672, "rw-rwx-w-", },
                { 0673, "rw-rwx-wx", },
                { 0674, "rw-rwxr--", },
                { 0675, "rw-rwxr-x", },
                { 0676, "rw-rwxrw-", },
                { 0677, "rw-rwxrwx", },
                { 0700, "rwx------", },
                { 0701, "rwx-----x", },
                { 0702, "rwx----w-", },
                { 0703, "rwx----wx", },
                { 0704, "rwx---r--", },
                { 0705, "rwx---r-x", },
                { 0706, "rwx---rw-", },
                { 0707, "rwx---rwx", },
                { 0710, "rwx--x---", },
                { 0711, "rwx--x--x", },
                { 0712, "rwx--x-w-", },
                { 0713, "rwx--x-wx", },
                { 0714, "rwx--xr--", },
                { 0715, "rwx--xr-x", },
                { 0716, "rwx--xrw-", },
                { 0717, "rwx--xrwx", },
                { 0720, "rwx-w----", },
                { 0721, "rwx-w---x", },
                { 0722, "rwx-w--w-", },
                { 0723, "rwx-w--wx", },
                { 0724, "rwx-w-r--", },
                { 0725, "rwx-w-r-x", },
                { 0726, "rwx-w-rw-", },
                { 0727, "rwx-w-rwx", },
                { 0730, "rwx-wx---", },
                { 0731, "rwx-wx--x", },
                { 0732, "rwx-wx-w-", },
                { 0733, "rwx-wx-wx", },
                { 0734, "rwx-wxr--", },
                { 0735, "rwx-wxr-x", },
                { 0736, "rwx-wxrw-", },
                { 0737, "rwx-wxrwx", },
                { 0740, "rwxr-----", },
                { 0741, "rwxr----x", },
                { 0742, "rwxr---w-", },
                { 0743, "rwxr---wx", },
                { 0744, "rwxr--r--", },
                { 0745, "rwxr--r-x", },
                { 0746, "rwxr--rw-", },
                { 0747, "rwxr--rwx", },
                { 0750, "rwxr-x---", },
                { 0751, "rwxr-x--x", },
                { 0752, "rwxr-x-w-", },
                { 0753, "rwxr-x-wx", },
                { 0754, "rwxr-xr--", },
                { 0755, "rwxr-xr-x", },
                { 0756, "rwxr-xrw-", },
                { 0757, "rwxr-xrwx", },
                { 0760, "rwxrw----", },
                { 0761, "rwxrw---x", },
                { 0762, "rwxrw--w-", },
                { 0763, "rwxrw--wx", },
                { 0764, "rwxrw-r--", },
                { 0765, "rwxrw-r-x", },
                { 0766, "rwxrw-rw-", },
                { 0767, "rwxrw-rwx", },
                { 0770, "rwxrwx---", },
                { 0771, "rwxrwx--x", },
                { 0772, "rwxrwx-w-", },
                { 0773, "rwxrwx-wx", },
                { 0774, "rwxrwxr--", },
                { 0775, "rwxrwxr-x", },
                { 0776, "rwxrwxrw-", },
                { 0777, "rwxrwxrwx", },
                { 01000, "---------", },
                { -1, "rwxrwxrwx", },
        };
        return Arrays.asList(parameters);
    }

    @Test
    public void testFromMask() {
        assertEquals(permissions, PosixFilePermissionSupport.fromMask(mask));
    }

    @Test
    public void testToMask() {
        // don't test toMask for 01000 or -1
        if (0 <= mask && mask <= 0777) {
            assertEquals(mask, PosixFilePermissionSupport.toMask(permissions));
        }
    }

    @Test
    public void testHasPermission() {
        for (PosixFilePermission permission : ALL_PERMISSIONS) {
            assertEquals(permissions.contains(permission), PosixFilePermissionSupport.hasPermission(mask, permission));
        }
    }
}
